name: burt_network
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.5

# Add regular dependencies here.
dependencies:
  build_runner: ^2.4.6
  logger: ^1.4.0
  meta: ^1.9.1
  protobuf: ^3.0.0
  protoc_builder: ^0.4.0
  # path: ^1.8.0

dev_dependencies:
  test: ^1.21.0
  very_good_analysis: ^5.0.0+1
